### PR TITLE
Updated installing PASW tile

### PR DESCRIPTION
**Pull request by awmartin**
- Inserted necessary disk sizing step, which applies to all IaaSes.
- Removed A/V config, which cannot be done during this process.
- Separated steps to accommodate disk sizing table and text.
- Referenced the pre-existing stemcell upload steps from PAS.

### CODE REVIEW

**Comment by awmartin** [comment]
@pspinrad Mind to take a look at this PR? We have internal folks reading the docs, and these changes we'd like to get feedback on from them.

**Comment by pspinrad** [comment]
Thanks @awmartin -- sorry for delay.  No more need for instrux to remove antivirus collision problem?

**Comment by awmartin** [comment]
That particular problem can’t be addressed when installing the tile. It can
only be addressed as part of building a stemcell or configuring add-ons.

We’ll need to document it, but more fully and in a different place.

**Comment by pspinrad** [comment]
Good to know-- thanks.

**Pull request merged**
