### PR TITLE
Add notes about PAS mTLS and disabling TCP routing

### PR DESCRIPTION
**Pull request by jfeeny**

### CODE REVIEW

**Comment by genevieve** [comment]
The sentence:
> If you enable mutual TLS here. You must also enable mutual TLS in the App Container Config of the PAS tile.
might be read better as:
> If you enable mutual TLS here, you must also enable mutual TLS in the App Container Config of the PAS tile.

**Comment by mlimonczenko** [comment]
Thank you!

**Comment by mlimonczenko** [comment]
@jfeeny and @genevievel, [you can find the change here](https://docs-pcf-staging.cfapps.io/platform/application-service-windows/2-8/installing.html#enable-route-integrity). I think that there's a bit of note overload here. I encourage finding a way to consolidate them or make them not look so heavy.

**Comment by kartiklunkad26** [comment]
@mlimonczenko This doesn't seem needed considering v2.3 is out of support at this point. 
```Note: To support mTLS app identity verification, you need v2.3 or later of both and Pivotal Platform Isolation Segment (IST). The Gorouter and Diego Cell components in v2.2 and earlier do not support mTLS handshakes.```

**Pull request merged**
