### PR TITLE
Update docs for IWA + gorouter support.

### PR DESCRIPTION
**Pull request by geofffranks**
This should get published alongside/after the release of RT-2024-004, since it references code not present until those versions are available.

### CODE REVIEW

**Comment by anita-flegg** [comment]
@geofffranks , would you mind putting this PR in DRAFT state until you are ready to have it published, please?
We wouldn't want to get carried away and integrate it too early! :)

**Comment by jrussett** [comment]
Hey @anita-flegg and @geofffranks 👋 

This PR can now be merged in as the requisite code changes were released yesterday, e.g. [TAS 5.0.8](https://docs.vmware.com/en/VMware-Tanzu-Application-Service/5.0/tas-for-vms/runtime-rn.html#508-1)

**Comment by anita-flegg** [comment]
Thanks, @jrussett 
@fifthposition , this is ready for merge and edit.

**Comment by fifthposition** [comment]
thanks @geofffranks

**Pull request merged**
